# Generated by Django 5.2.9 on 2025-12-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bread_preferences_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
