# Generated by Django 5.2.9 on 2025-12-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='character_type',
            field=models.CharField(default='hamster', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
