# Generated by Django 5.2.9 on 2025-12-23 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_character_type_user_exp_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ACTION', '행동 기반'), ('REGION', '지역 기반'), ('EVENT', '희귀/이벤트')], default='ACTION', max_length=10)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('condition_threshold', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='character_type',
        ),
        migrations.AddField(
            model_name='user',
            name='level_title',
            field=models.CharField(default='아기빵쥐', max_length=50),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(related_name='holders', through='accounts.UserBadge', to='accounts.badge'),
        ),
    ]
