# Generated by Django 5.2.9 on 2025-12-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='taste_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
