# Generated by Django 5.2.4 on 2025-12-22 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_taste_tags'),
        ('stores', '0005_store_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store'),
        ),
    ]
