# Generated by Django 5.2.9 on 2025-12-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='menu_items',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
