# Generated by Django 5.2.9 on 2025-12-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
