# Generated by Django 5.2.9 on 2025-12-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_keyword_product_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='preview_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
