# Generated by Django 5.2.9 on 2025-12-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='popular_menu_items',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
