# Generated by Django 5.2.9 on 2025-12-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/images/%Y/%m/%d/'),
        ),
    ]
